// Enrichissement modeles[] pour les codes de la base.
// Genere automatiquement via scripts/integrate-modeles-enrichment.mjs
// a partir d'un workflow LLM (10 agents paralleles, 07/06/2026).
//
// Format : { marqueSlug -> { code -> [familles de modeles] } }
// Les codes absents de ce map = generiques marque (visibles sur tous modeles).
// Les codes presents = filtres : visibles uniquement si modeleQuery matche
//   au moins un des prefixes listes (matching prefix bidirectionnel).
//
// Merge fait au runtime dans search.ts via getEnrichedModeles().

export const MODELES_ENRICHMENT: Record<string, Record<string, string[]>> = {
  "atlantic": {
    "10": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Naia", "Naema"],
    "107": ["Naia", "Naema"],
    "11": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja"],
    "112": ["Naia", "Naema"],
    "118": ["Naia", "Naema"],
    "119": ["Naia", "Naema"],
    "12": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja"],
    "121": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "13": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja"],
    "135": ["Naia", "Naema"],
    "136": ["Naia", "Naema"],
    "15": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "16": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja"],
    "17": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja"],
    "20": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja", "Takao"],
    "21": ["Takao", "TPH", "TCO", "Naviclim"],
    "25": ["Naia", "Naema"],
    "30": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Naia", "Naema"],
    "30.1": ["Calypso", "Odyssee"],
    "30.2": ["Calypso", "Odyssee"],
    "30.3": ["Calypso", "Odyssee"],
    "30.4": ["Calypso", "Odyssee"],
    "31": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "32": ["Takao", "TPH", "TCO", "Naviclim"],
    "34": ["Alfea Hybrid Duo", "Alfea Excellia Duo", "Alfea Extensa Duo"],
    "356": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "369": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "370": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Loria", "Maradja"],
    "38": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "40": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Naia", "Naema"],
    "46": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Naia", "Naema"],
    "50": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Naia", "Naema"],
    "50.1": ["Calypso", "Odyssee"],
    "516": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "52.3": ["Calypso", "Odyssee"],
    "53.1": ["Calypso", "Odyssee"],
    "58": ["Naia", "Naema"],
    "60": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo", "Naia", "Naema"],
    "68": ["Naia", "Naema"],
    "69": ["Naia", "Naema"],
    "7": ["Naia", "Naema"],
    "86": ["Takao", "TPH", "TCO", "Naviclim"],
    "A1": ["Takao", "TPH", "TCO", "Naviclim"],
    "AP": ["Naia", "Naema"],
    "EE": ["Takao", "TPH", "TCO", "Naviclim"],
    "ERR 15": ["Calypso", "Odyssee"],
    "ERR 24": ["Calypso", "Odyssee"],
    "G7": ["Alfea Excellia", "Alfea Extensa"],
    "G8": ["Alfea Excellia", "Alfea Extensa"],
    "G9": ["Alfea Excellia", "Alfea Extensa", "Alfea Hybrid Duo"],
    "W20": ["Calypso", "Odyssee"],
    "W21": ["Calypso", "Odyssee"],
    "W22": ["Calypso", "Odyssee"],
    "W23": ["Calypso", "Odyssee"],
    "W27": ["Calypso", "Odyssee"],
  },
  "bosch": {
    "0Y 276": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "1C": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "2E 207": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "2P 212": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "3A 264": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "3C": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "4C 224": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "4U 222": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "4Y 223": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "6A 227": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "6L 229": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "9A 235": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "9L 234": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "A7 / CL": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "Ad": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "B3": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "C6 / C7": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "CE": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "E01": ["Compress 7000", "Compress 6000", "Compress 3000", "CS", "AWO", "AWB", "AWS"],
    "E02": ["Compress 7000", "Compress 6000", "Compress 3000", "CS", "AWO", "AWB", "AWS"],
    "E03": ["Compress 7000", "Compress 6000", "Compress 3000", "CS", "AWO", "AWB", "AWS"],
    "E04": ["Compress 7000", "Compress 6000", "Compress 3000", "CS", "AWO", "AWB", "AWS"],
    "E06": ["Compress 7000", "Compress 6000", "Compress 3000", "CS", "AWO", "AWB", "AWS"],
    "E07": ["Compress 7000", "Compress 6000", "Compress 3000", "CS", "AWO", "AWB", "AWS"],
    "E9": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "EA": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "F7 / 6C 228": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "H07": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
    "P1 / P2": ["Compress 7000", "Compress 6000", "Compress 3000"],
    "d7": ["GB172", "Cerapur", "ZSB", "ZWB", "CR"],
  },
  "carrier": {
    "10H4": ["38VMA"],
    "33": ["30RB", "30XW", "30RBS", "30RQ"],
    "41": ["30RB", "30XW", "30RQ"],
    "73": ["38VMA", "40VMA", "MMD", "MMU"],
    "74": ["38VMA", "40VMA", "MMD", "MMU"],
    "ATL": ["30RB", "30XW", "EWAQ"],
    "CO-E1": ["30RB", "30RQ", "30XW"],
    "E0": ["38QUS", "42QHC", "40VMA"],
    "E2": ["38QUS", "42QHC", "40VMA"],
    "E3": ["42QHC", "40VMA", "40QAQ"],
    "E4": ["38QUS", "42QHC", "40VMA", "40QAQ"],
    "E5": ["38QUS", "42QHC", "40VMA", "40QAQ"],
    "E6": ["38QUS", "38VMA", "40VMA"],
    "E7": ["38QUS", "38VMA", "40VMA"],
    "E8": ["38VMA", "40VMA", "MMD", "MMU"],
    "EC": ["38QUS", "38VMA", "40VMA"],
    "EE": ["42QHC", "40QAQ", "40KMC"],
    "F0": ["38QUS", "38VMA", "40VMA"],
    "F1": ["38QUS", "38VMA", "40VMA"],
    "F2": ["38QUS", "38VMA", "40VMA"],
    "F3": ["38QUS", "38VMA", "40VMA"],
    "F4": ["38QUS", "38VMA", "40VMA"],
    "F4-AquaSnap": ["30RB", "30RQ", "30RBS"],
    "F5": ["38QUS", "38VMA", "40VMA"],
    "F6": ["42QHC", "40VMA", "40QAQ"],
    "H0": ["38VMA", "40VMA"],
    "H2": ["38VMA", "MMD"],
    "H3": ["38VMA", "MMD"],
    "H5": ["38VMA", "MMD"],
    "H6": ["38VMA", "MMD"],
    "H8": ["38VMA", "MMD"],
    "H9": ["38VMA", "MMD"],
    "Hb": ["38VMA", "MMD"],
    "P-01": ["30RB", "30RQ", "30XW", "EWAQ"],
    "P-05": ["30RB", "30RQ", "30XW"],
    "P0": ["38QUS", "38VMA", "40VMA"],
    "P1": ["38QUS", "38VMA", "40VMA"],
    "P2": ["38QUS", "38VMA", "40VMA"],
    "P3": ["38QUS", "38VMA", "40VMA"],
    "P4": ["38QUS", "38VMA", "40VMA"],
    "P5": ["38VMA", "40VMA", "MMD", "MMU"],
    "P6": ["38QUS", "38VMA", "40VMA"],
    "P7": ["38QUS", "38VMA", "40VMA"],
    "P8": ["38QUS", "38VMA", "40VMA"],
    "P9": ["38QUS", "38VMA", "40VMA"],
    "PR-01": ["30RB", "30RQ", "30XW"],
    "PR-04": ["30RB", "30RQ", "30XW"],
    "TH-10": ["30RB", "30RQ", "30RBS"],
    "TH-12": ["30RB", "30RQ", "30RBS"],
  },
  "chaffoteaux": {
    "1 16": ["Talia Green System", "Pigma", "Inoa"],
    "2 01": ["Mira C Green", "Pigma", "Inoa", "ELXIA", "Niagara C Green"],
    "2 03": ["Talia Green System", "Niagara C Green", "Pharos"],
    "2 09": ["Talia Green System", "Niagara C Green", "Pharos", "Arianext"],
    "2 P7": ["Arianext", "Nimbus"],
    "9 02": ["Arianext", "Nimbus", "Pharos"],
    "9 18": ["Arianext", "Nimbus", "Pharos"],
    "9 23": ["Arianext", "Nimbus", "Pharos"],
    "9 24": ["Arianext", "Nimbus", "Pharos"],
    "9 33": ["Arianext", "Nimbus", "Pharos"],
    "9 37": ["Arianext", "Nimbus", "Pharos"],
  },
  "daikin": {
    "89-05": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "8H-03": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "A3": ["FXFQ", "FCQ", "FCAG", "FUQ", "FFA", "FBA", "FDA", "FHA"],
    "A7": ["FTXS", "FTXM", "FTKM", "FTX", "FXFQ", "FCQ", "FFA", "FHA", "FNA"],
    "AA": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "AE": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "AF": ["FXFQ", "FCQ", "FCAG", "FUQ", "FFA"],
    "AH": ["FXFQ", "FCQ", "FCAG"],
    "AJ-03": ["EHVH", "EHBH", "EHSH"],
    "EC": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "F9": ["RXYQ", "RXYSQ", "RXYQQ"],
    "HC": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "HJ": ["EHVH", "EHBH", "EHSH"],
    "J1": ["RXYQ", "RXYSQ", "RXYQQ", "RZQ", "RZQG", "RZAG", "LRYEQ"],
    "J9": ["RXYQ", "RXYSQ", "RXYQQ"],
    "JA": ["RXYQ", "RXYSQ", "RXYQQ", "RZQ", "RZQG", "RZAG", "LRYEQ"],
    "JC": ["RXYQ", "RXYSQ", "RXYQQ", "RZQ", "RZQG", "RZAG", "LRYEQ"],
    "M1": ["DCS601", "DCM601", "BRC"],
    "M8": ["DCS601", "DCM601", "BRC"],
    "MA": ["DCS601", "DCM601"],
    "PA": ["EHVH", "EHBH", "EHSH", "EBLQ", "EDLQ"],
    "U3": ["RXYQ", "RXYSQ", "RXYQQ"],
    "U7": ["RXYQ", "RXYSQ", "RXYQQ", "LRYEQ"],
    "UC": ["DCS601", "DCM601"],
    "UE": ["DCS601", "DCM601", "BRC"],
  },
  "de-dietrich": {
    "A01.23": ["Innovens", "Modulens", "Vivadens"],
    "A02.06": ["Innovens", "Modulens", "Vivadens"],
    "A02.34": ["Innovens", "Modulens"],
    "E01": ["Inisia", "Innovens", "Modulens", "Vivadens", "Twineo"],
    "E02": ["Inisia", "Innovens", "Modulens", "Vivadens", "Twineo", "NEOVO"],
    "E03": ["Inisia", "Innovens", "Modulens", "Vivadens", "NEOVO"],
    "E04": ["Inisia", "Innovens", "Modulens", "Vivadens", "Twineo"],
    "E10": ["Inisia", "Innovens", "Modulens", "Vivadens", "Twineo"],
    "E15": ["Innovens", "Modulens", "Vivadens"],
    "E25": ["Inisia", "Innovens", "Modulens", "Vivadens"],
    "E32": ["Innovens", "Modulens", "Vivadens"],
    "E35": ["Inisia", "Innovens", "Modulens", "Vivadens", "Twineo"],
    "E96": ["Innovens", "Modulens", "Vivadens"],
    "E99": ["Innovens", "Modulens", "Vivadens"],
    "H.06.01": ["Strateo"],
    "H00.06": ["Innovens", "Modulens", "Vivadens", "Twineo"],
    "H00.16": ["Innovens", "Modulens", "Vivadens", "Twineo"],
    "H00.32": ["Innovens", "Modulens", "Vivadens", "Strateo", "Twineo"],
    "H01.05": ["Innovens", "Modulens", "Vivadens"],
    "H01.08": ["Innovens", "Modulens", "Vivadens"],
    "H01.09": ["Innovens", "Modulens", "Vivadens"],
    "H01.14": ["Innovens", "Modulens", "Vivadens"],
    "H02.02": ["Innovens", "Modulens", "Vivadens"],
    "H03.05": ["Innovens", "Modulens", "Vivadens"],
    "L01": ["Innovens", "Modulens", "Vivadens"],
    "L02": ["Innovens", "Modulens", "Vivadens"],
    "L250": ["Innovens", "Modulens", "Vivadens"],
    "L251": ["Innovens", "Modulens", "Vivadens"],
    "L40": ["Innovens"],
  },
  "elm-leblanc": {
    "104": ["Megalis", "Egalis", "Mira Green"],
    "105": ["Megalis", "Egalis", "Mira Green"],
    "225": ["Megalis", "Egalis"],
    "A2": ["Acleis", "Megalia"],
    "A4": ["Acleis", "Megalia"],
    "B1": ["Megalis", "Egalis"],
    "C3": ["Megalis", "Egalis", "Acleis"],
    "C6": ["Megalis", "Egalis", "Acleis"],
    "D3": ["Megalis", "Egalis"],
    "D4": ["Megalis", "Egalis"],
    "D7": ["Megalis", "Egalis"],
    "F13": ["Megalis", "Egalis"],
    "F22": ["Megalis", "Egalis", "Mira Green"],
  },
  "frisquet": {
    "Anomalie capteur DP Air": ["Prestige Condensation", "Prestige Visio"],
    "Anomalie capteur DP Gaz": ["Prestige Condensation", "Prestige Visio"],
    "Anomalie sonde gaz brûlés": ["Prestige Condensation", "Prestige Visio"],
    "Anomalie vanne 4 voies": ["Prestige Condensation", "Prestige Visio", "Hydromotrix"],
    "Anomalie vanne auto-zéro": ["Prestige Condensation", "Prestige Visio"],
    "Anomalie ventilateur": ["Prestige Condensation", "Prestige Visio", "Hydromotrix"],
    "Circuit air / Gaz brûlés": ["Prestige Condensation", "Prestige Visio", "Hydromotrix"],
    "Défaut configuration": ["Hydromotrix"],
    "Panne non identifiée": ["Prestige Condensation", "Prestige Visio"],
    "Plus d'affichage": ["Prestige Visio"],
    "Température gaz brûlés": ["Prestige Condensation", "Prestige Visio"],
    "Tous voyants clignotants": ["Hydroconfort", "Hydromotrix"],
    "Voyant orange clignotant": ["Hydroconfort", "Hydromotrix"],
    "Voyant rouge clignotant": ["Hydroconfort", "Hydromotrix"],
    "Voyant rouge fixe": ["Hydroconfort", "Hydromotrix"],
    "Voyant vert clignotant": ["Hydroconfort", "Hydromotrix"],
  },
  "fujitsu": {
    "40": ["AUYG", "ARYG", "ABYG"],
    "A1": ["ASYG", "ASUG"],
    "A3": ["ASYG", "ASUG"],
    "E1:00": ["ASYG", "ASUG", "AJY", "AUYG", "ARYG", "ABYG"],
    "E1:01": ["ASYG", "ASUG", "AJY", "AUYG", "ARYG", "ABYG"],
    "E1:03": ["ASYG", "ASUG", "AJY"],
    "E1:04": ["ASYG", "ASUG", "AJY"],
    "E1:07": ["ASYG", "ASUG", "AJY"],
    "E1:15": ["AJY", "WSY", "WGY"],
    "E1:17": ["ASYG", "ASUG", "AJY"],
    "E1:20": ["ASYG", "ASUG", "AJY"],
    "E1:30": ["ASYG", "ASUG", "AJY"],
    "E1:31": ["ASYG", "ASUG", "AJY"],
    "E22": ["AJY"],
    "E2:00": ["ASYG", "AUYG", "ARYG", "ABYG"],
    "E2:01": ["ASYG", "AUYG", "ARYG", "ABYG"],
    "E2:05": ["ASYG", "AUYG", "ARYG", "ABYG"],
    "E2:09": ["AUYG", "ARYG", "ABYG"],
    "E3:07": ["AJY"],
    "WS-10": ["WSY", "WGY"],
    "WS-127": ["WSY", "WGY"],
    "WS-212": ["WSY", "WGY"],
    "WS-356": ["WSY", "WGY"],
    "WS-50": ["WSY", "WGY"],
    "WS-516": ["WSY", "WGY"],
  },
  "hitachi": {
    "05": ["RAS-XHN", "RAS-FSXN", "Set Free", "RAS-DJ"],
    "06": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "0A": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "0B": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "0C": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "11": ["RPK", "RPI", "RCI", "RPC", "RAS-S", "RAS-DJ"],
    "12": ["RPK", "RPI", "RCI", "RPC", "RAS-S", "RAS-DJ"],
    "13": ["RPK", "RPI", "RCI", "RPC", "RAS-S", "RAS-DJ"],
    "14": ["RPK", "RPI", "RCI", "RPC", "RAS-S", "RAS-DJ"],
    "19": ["RPK", "RPI", "RCI", "RPC", "RAS-S", "RAS-DJ"],
    "202": ["RWH", "RWD", "RWM", "Yutaki"],
    "205": ["RWH", "RWD", "RWM", "Yutaki"],
    "21": ["RAS-XHN", "RAS-FSXN", "Set Free", "RAS-DJ"],
    "29": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "35": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "39": ["RAS-DJ", "RAS-S"],
    "70": ["RWH", "RWD", "RWM", "Yutaki"],
    "B1": ["RAS-XHN", "RAS-FSXN", "Set Free"],
    "B5": ["RAS-XHN", "RAS-FSXN", "Set Free"],
  },
  "lg": {
    "CH04": ["ARNU", "CT", "AS-W"],
    "CH07": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH08": ["ARNU", "CT", "AS-W", "FM"],
    "CH09": ["ARNU", "CT", "AS-W", "FM", "US"],
    "CH10": ["ARUN", "ARUM", "ARWN", "AS-W", "FM", "US", "HM", "HU"],
    "CH105": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH106": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH113": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH13": ["HM", "HU"],
    "CH14": ["HM", "HU"],
    "CH15": ["HM", "HU"],
    "CH16": ["HM", "HU"],
    "CH18": ["HM", "HU"],
    "CH19": ["HM", "HU"],
    "CH20": ["HM", "HU"],
    "CH200": ["ARUN", "ARUM", "ARWN"],
    "CH42": ["ARUN", "ARUM", "ARWN", "FM", "HM", "HU"],
    "CH43": ["ARUN", "ARUM", "ARWN", "FM", "HM", "HU"],
    "CH53": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH57": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH90": ["ARUN", "ARUM", "ARWN", "FM"],
    "CH91": ["ARUN", "ARUM", "ARWN", "FM"],
    "HL": ["ARNU", "CT"],
  },
  "mitsubishi": {
    "1102": ["PUHY", "PURY", "PUHZ-W"],
    "1300": ["PUHY", "PURY", "PUHZ-W"],
    "1302": ["PUHY", "PURY", "PUHZ-W"],
    "1500": ["PUHY", "PURY"],
    "1501": ["PUHY", "PURY"],
    "2500": ["EHST", "EHPX", "QUHZ"],
    "2502": ["PEFY", "PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD"],
    "2510": ["EHST", "EHPX", "QUHZ"],
    "4220": ["PUHY", "PURY", "PUHZ-W"],
    "4230": ["PUHY", "PURY", "PUHZ-W"],
    "4240": ["PUHY", "PURY", "PUHZ-W"],
    "4250": ["PUHY", "PURY", "PUHZ-W"],
    "4260": ["PUHY", "PURY", "PUHZ-W"],
    "5000": ["EHST", "EHPX", "QUHZ", "PUHZ-W"],
    "5030": ["EHST", "EHPX", "QUHZ"],
    "5050": ["EHST", "EHPX", "QUHZ"],
    "5104": ["PUHY", "PURY"],
    "5111": ["CMB", "CMY"],
    "5112": ["CMB", "CMY"],
    "5115": ["CMB", "CMY"],
    "5116": ["CMB", "CMY"],
    "6602": ["EHST", "EHPX", "QUHZ", "PUHZ-W"],
    "7100": ["PUHY", "PURY"],
    "7101": ["PUHY", "PURY"],
    "7102": ["PUHY", "PURY"],
    "7110": ["PUHY", "PURY"],
    "E9": ["MSZ-EF", "MSZ-AP", "MSZ-LN", "PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PUHZ-W"],
    "EA": ["MSZ-EF", "MSZ-AP", "MSZ-LN", "PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PUHZ-W"],
    "EB": ["MSZ-EF", "MSZ-AP", "PLA-M", "PEA-M", "PCA", "PEAD", "PUHZ-W"],
    "EC": ["PUHY", "PURY", "PUHZ-W"],
    "ED": ["PUHY", "PURY"],
    "EF": ["PUHY", "PURY", "PEFY", "PLA-M"],
    "F3": ["PUHY", "PURY", "PUHZ-W"],
    "F5": ["PUHY", "PURY", "PUHZ-W"],
    "F9": ["PUHY", "PURY", "PUHZ-W"],
    "L3": ["PUHZ-W", "EHST", "EHPX", "QUHZ"],
    "L8": ["PUHZ-W", "EHST", "EHPX", "QUHZ"],
    "L9": ["PUHZ-W", "EHST", "EHPX", "QUHZ"],
    "P1": ["PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PEFY", "PCFY", "PMFY", "PKFY"],
    "P2": ["PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PEFY", "PCFY", "PMFY", "PKFY"],
    "P4": ["PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PEFY", "PCFY", "PMFY"],
    "P5": ["PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PEFY", "PCFY", "PMFY"],
    "P6": ["MSZ-EF", "MSZ-AP", "MSZ-LN", "PLA-M", "PSA-M", "PEA-M", "PCA", "PEAD", "PEFY"],
    "P8": ["PUHY", "PURY", "PUHZ-W", "PEFY", "PLA-M"],
    "U2": ["PUHY", "PURY", "PUHZ-W"],
    "U4": ["PUHY", "PURY", "PUHZ-W"],
    "U5": ["PUHY", "PURY", "PUHZ-W"],
    "U6": ["PUHY", "PURY", "PUHZ-W"],
    "U8": ["PUHY", "PURY", "PUHZ-W"],
  },
  "mitsubishi-heavy": {
    "E16": ["FDT", "FDK", "SRK"],
    "E19": ["FDT", "FDU", "FDE"],
    "E2": ["FDC", "FDT", "FDU", "FDE", "FDF"],
    "E21": ["FDT"],
    "E3": ["FDC", "FDT", "FDU"],
    "E32": ["FDC"],
    "E35": ["FDC", "SRC"],
    "E36": ["FDC", "SRC"],
    "E37": ["FDC", "SRC"],
    "E38": ["FDC", "SRC"],
    "E39": ["FDC", "SRC"],
    "E40": ["FDC", "SRC"],
    "E42": ["FDC"],
    "E43": ["FDC"],
    "E45": ["FDC"],
    "E47": ["FDC"],
    "E48": ["FDC", "SRC"],
    "E49": ["FDC", "SRC"],
    "E51": ["FDC", "SRC"],
    "E53": ["FDC", "SRC"],
    "E54": ["FDC", "SRC"],
    "E55": ["FDC", "SRC"],
    "E56": ["FDC", "SRC"],
    "E57": ["FDC", "SRC"],
    "E58": ["FDC", "SRC"],
    "E59": ["FDC", "SRC"],
    "E6": ["FDT", "FDU", "FDE", "FDF", "SRK"],
    "E60": ["FDC", "SRC"],
    "E61": ["FDC"],
    "E63": ["FDC"],
    "E7": ["FDT", "FDU", "FDE", "FDF", "SRK"],
    "E9": ["FDT", "FDU", "FDE", "FDF"],
    "P5": ["FDC", "SRC"],
  },
  "panasonic": {
    "F17": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-NZ", "CS-Z71", "S-71MU2E5B", "S-71PE3R"],
    "F25": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-Z71", "S-71MU2E5B", "S-71PE3R"],
    "F36": ["WH-MDC", "WH-UD", "WH-MXC"],
    "F43": ["WH-MDC", "WH-UD", "WH-MXC"],
    "F95": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-Z71", "S-71MU2E5B", "S-71PE3R", "U-", "S-EM"],
    "H12": ["CS-MXZ", "U-", "S-EM", "S-MM"],
    "H14": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-NZ", "CS-Z71", "S-71MU2E5B", "S-71PE3R"],
    "H19": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-NZ", "CS-Z71", "S-71MU2E5B", "S-71PE3R"],
    "H20": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H23": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-NZ", "CS-Z71", "S-71MU2E5B", "S-71PE3R"],
    "H36": ["U-", "S-EM", "S-MM"],
    "H42": ["U-", "S-EM", "S-MM"],
    "H43": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H44": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H62": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H67": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H68": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H70": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H72": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H75": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H91": ["WH-MDC", "WH-UD", "WH-MXC"],
    "H99": ["CS-XZ", "CS-Z", "CS-MXZ", "CS-NZ", "CS-Z71"],
  },
  "samsung": {
    "E108": ["DVM", "AM", "AJ", "FJM"],
    "E143": ["AR", "Wind-Free"],
    "E153": ["AC", "AJ", "FJM"],
    "E154": ["AR", "AQ", "AC", "AJ"],
    "E202": ["AJ", "FJM"],
    "E203": ["DVM", "AM", "AE", "EHS"],
    "E231": ["DVM", "AM", "AE", "EHS"],
    "E251": ["DVM", "AM", "AE", "EHS"],
    "E291": ["DVM", "AM", "AE", "EHS"],
    "E296": ["DVM", "AM", "AE", "EHS"],
    "E308": ["DVM", "AM", "AE", "EHS"],
    "E311": ["DVM", "AM", "AE", "EHS"],
    "E320": ["DVM", "AM", "AE", "EHS"],
    "E416": ["DVM", "AM", "AC"],
    "E419": ["DVM", "AM", "AE", "EHS"],
    "E425": ["DVM", "AM"],
    "E438": ["DVM", "AE", "EHS"],
    "E439": ["DVM", "AM", "AE", "EHS"],
    "E440": ["AE", "EHS", "DVM"],
    "E441": ["AE", "EHS", "DVM"],
    "E443": ["DVM", "AM", "AE", "EHS"],
    "E458": ["DVM", "AM", "AE", "EHS"],
    "E475": ["DVM", "AM"],
    "E554": ["DVM", "AM", "AE", "EHS"],
    "E901": ["AE", "EHS"],
    "E902": ["AE", "EHS"],
    "E903": ["AE", "EHS"],
    "E904": ["AE", "EHS"],
    "E906": ["AE", "EHS"],
    "E911": ["AE", "EHS"],
    "E912": ["AE", "EHS"],
  },
  "saunier-duval": {
    "F.0": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.1": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.10": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.11": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.12": ["Themaplus condens", "Thelia tubo", "Isofast condens", "Isotwin condens"],
    "F.13": ["Themis condens", "Themaplus condens", "Isotwin condens"],
    "F.14": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens"],
    "F.15": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.19": ["Themaplus condens", "Thelia tubo", "Isofast condens", "Isotwin condens"],
    "F.2": ["Thema Classic", "Thelia tubo"],
    "F.20": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.22": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.23": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.24": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.25": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.26": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.27": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.28": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.29": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens", "Initia"],
    "F.32": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.36": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.4": ["Thema Classic", "Thelia tubo", "Initia"],
    "F.5": ["Themis condens", "Themaplus condens", "Thema Classic", "Thelia tubo", "Isofast condens", "Isotwin condens"],
    "F.55": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.6": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.61": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.62": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.67": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.68": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.71": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.72": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.73": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.74": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.75": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens", "Initia"],
    "F.77": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.83": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.84": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.85": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.9": ["Themis condens", "Themaplus condens", "Isofast condens", "Isotwin condens"],
    "F.99": ["Themaplus condens", "Isofast condens", "Isotwin condens"],
  },
  "stiebel-eltron": {
    "1": ["WPL", "WPF", "HPA"],
    "11": ["WPL", "WPF", "HPA"],
    "13": ["WPL", "HPA"],
    "16": ["SHZ", "HSBC"],
    "17": ["WPL", "WPF", "HPA"],
    "19": ["WPL", "WPF", "HPA"],
    "2": ["SHZ"],
    "20": ["WPL", "WPF", "HPA"],
    "21": ["WPL", "WPF", "HPA"],
    "256": ["WPL", "WPF", "HPA"],
    "3 (PROTECTION HORS GEL)": ["WPF"],
    "32": ["SHZ", "HSBC"],
    "4": ["SHZ"],
    "5": ["WPL", "WPF", "HPA"],
    "512": ["WPF"],
    "7": ["WPL", "WPF", "HPA"],
    "E1": ["WPL", "WPF", "HPA", "SHZ"],
    "E128": ["WPL", "WPF", "HPA"],
    "E130": ["WPF"],
    "E16": ["WPL", "WPF", "HPA"],
    "E2": ["SHZ"],
    "E4": ["WPL", "WPF", "HPA"],
    "E64": ["WPL", "WPF", "HPA"],
    "E70": ["WPL", "WPF", "HPA", "LWZ"],
    "E71": ["WPL", "WPF", "HPA"],
    "E72": ["WPL", "WPF", "HPA", "LWZ"],
    "E73": ["WPL", "WPF", "HPA", "LWZ"],
    "E76": ["WPL", "WPF", "HPA", "HSBC", "LWZ"],
    "E77": ["WPL", "WPF", "HPA", "LWZ"],
  },
  "toshiba": {
    "1C": ["RAS-PKVPG", "RAS-13PKVSG", "RAS"],
    "1E": ["RAS-PKVPG", "RAS-13PKVSG", "RAS"],
    "A01": ["HWS-P", "HWS-1404XWH"],
    "A02": ["HWS-P", "HWS-1404XWH"],
    "A03": ["HWS-P", "HWS-1404XWH"],
    "A04": ["HWS-P", "HWS-1404XWH"],
    "A05": ["HWS-P", "HWS-1404XWH"],
    "C12": ["MMY-MAP", "RAV"],
    "E07": ["MMY-MAP", "RAV"],
    "E12": ["MMY-MAP"],
    "E15": ["MMY-MAP"],
    "E16": ["MMY-MAP"],
    "E18": ["MMY-MAP"],
    "E19": ["MMY-MAP"],
    "E20": ["MMY-MAP"],
    "E23": ["MMY-MAP"],
    "E25": ["MMY-MAP"],
    "E26": ["MMY-MAP"],
    "E28": ["MMY-MAP"],
    "F01": ["MMY-MAP", "RAV", "RAS-PKVPG", "RAS"],
    "F02": ["MMY-MAP", "RAV"],
    "F03": ["MMY-MAP", "RAV"],
    "F04": ["MMY-MAP", "RAV"],
    "F10": ["MMY-MAP", "RAV"],
    "F29": ["MMY-MAP", "RAV"],
    "F31": ["MMY-MAP", "RAV"],
    "P03": ["MMY-MAP", "RAV"],
    "P04": ["MMY-MAP", "RAV", "RAS-PKVPG"],
    "P05": ["MMY-MAP", "RAV"],
    "P07": ["MMY-MAP", "RAV"],
    "P09": ["MMY-MAP", "RAV"],
    "P13": ["MMY-MAP"],
  },
  "trane": {
    "Hi PR": ["RTAC", "CGAM", "XTREME", "CGAX", "Voyager", "Odyssey", "Axiom"],
    "LOC": ["Voyager", "Odyssey", "Axiom"],
    "Lo PR": ["RTAC", "CGAM", "XTREME", "CGAX", "Voyager", "Odyssey", "Axiom"],
  },
  "vaillant": {
    "F.00": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.01": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.022": ["aroTHERM", "geoTHERM", "recoCOMPACT"],
    "F.10": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.11": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.13": ["ecoTEC", "ecoVIT", "uniSTOR"],
    "F.20": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.22": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.23": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.24": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.25": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.27": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.28": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.29": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.32": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.33": ["atmoTEC", "ecoCRAFT"],
    "F.61": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.62": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.67": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.68": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.71": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.72": ["ecoTEC", "atmoTEC", "ecoVIT", "ecoCRAFT"],
    "F.73": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.731": ["aroTHERM", "geoTHERM"],
    "F.74": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.75": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.77": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.819": ["aroTHERM"],
    "F.823": ["aroTHERM"],
    "F.83": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.84": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
    "F.85": ["ecoTEC", "ecoVIT", "ecoCRAFT"],
  },
};

export const MODELES_ENRICHMENT_META = {
  generatedAt: "2026-06-07",
  totalCodesEnrichies: 566,
  totalCodesTraites: 838,
  marquesCount: 20,
};
